name: Lint
on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Set up php${{ matrix.php-versions }}
      uses: shivammathur/setup-php@v1
    - name: Install Dependencies
      run: composer install --prefer-dist
    - name: Setup Nextcloud
      run: |
        mysql -u root -proot -e "CREATE DATABASE oc_autotest;"
        mysql -u root -proot -e "CREATE USER 'oc_autotest'@'localhost' IDENTIFIED BY '';"
        mysql -u root -proot -e "GRANT ALL ON oc_autotest.* TO 'oc_autotest'@'localhost';"
        cd ..
        git clone https://github.com/nextcloud/server.git --recursive --depth 1 -b master server
        cp -r notes server/apps/
        php server/occ maintenance:install --database-name oc_autotest --database-user oc_autotest --admin-user admin --admin-pass admin --database mysql --database-pass=''
        OC_PASS=test php server/occ user:add --password-from-env --display-name="Test" test
    - name: Setup Notes
      run: |
        php ../server/occ app:enable notes
        php ../server/occ app:check-code notes
    - name: Start Nextcloud server
      run: "php -S localhost:8080 -t ../server/ &"
    - name: Test API
      run: vendor/bin/phpunit --testdox tests/api/

